# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('jourseyNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('hundreds', models.PositiveIntegerField(default=0)),
                ('fifties', models.PositiveIntegerField(default=0)),
                ('highestScore', models.PositiveIntegerField(default=0)),
                ('totalMatch', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='common.Country')),
            ],
        ),
    ]
